image: reactnativecommunity/react-native-android

cache:
  paths:
    - node_modules/

before_script:
  - npm i -g envinfo && envinfo
  - yarn install

stages:
  - test
  - build

test:
  stage: test
  script:
    - CI=true yarn test

build:
  stage: build
  script:
    - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
    - yarn install
    - echo "$ANDROID_KEYSTORE" | base64 -d > android/app/gitlab-ci-android.keystore
    - echo "MYAPP_APP_ID=com.blixtwallet" >> android/gradle.properties
    - echo "MYAPP_RELEASE_STORE_FILE=gitlab-ci-android.keystore" >> android/gradle.properties
    - echo "MYAPP_RELEASE_KEY_ALIAS=gitlab-ci-key" >> android/gradle.properties
    - echo "MYAPP_RELEASE_STORE_PASSWORD=Spring15" >> android/gradle.properties
    - echo "MYAPP_RELEASE_KEY_PASSWORD=Spring15" >> android/gradle.properties
    - cd android && chmod +x gradlew
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - android/app/build/outputs/
