require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'BlixtWallet-macOS' do
  platform :macos, '11.5'
  use_native_modules!
  use_react_native!(
    :path => '../node_modules/react-native-macos',

    # To use Hermes, install the `hermes-engine-darwin` npm package, e.g.:
    #   $ yarn add 'hermes-engine-darwin@~0.5.3'
    #
    # Then enable this option:
    #   :hermes_enabled => true
  )

  # Pods specifically for macOS target

  # proto
  pod 'SwiftProtobuf', '~> 1.0'
end

#target 'BlixtWallet-iOS' do
#  platform :ios, '15'
#  use_native_modules!
#  use_react_native!(:path => '../node_modules/react-native-macos')
#
#  # Enables Flipper.
#  #
#  # Note that if you have use_frameworks! enabled, Flipper will not work and
#  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
#
#  # Pods specifically for iOS target
#end
