require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

project 'BlixtWallet',
        'DebugTestnet' => :debug,
        'ReleaseTestnet' => :release,
        'DebugFakelnd' => :debug,
        'ReleaseFakelnd' => :release,
        'DebugRegtest' => :debug,
        'ReleaseRegtest' => :release,
        'Debug' => :debug,
        'Release' => :release

target 'BlixtWallet' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # proto
  pod 'SwiftProtobuf', '~> 1.0'

  # react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"

  target 'BlixtWalletTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
#  use_flipper!
#  post_install do |installer|
#    flipper_post_install(installer)
#  end
end

target 'BlixtWallet-tvOS' do
  # Pods for BlixtWallet-tvOS

  target 'BlixtWallet-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
