name: Android build

on: [push, pull_request]

jobs:
  build_android:
    runs-on: ubuntu-18.04
    steps:
      - name: Build AAR
        uses: docker://blixtwallet/blixtwallet:latest
        with:
          args: |
            go get golang.org/x/tools/go/packages
            go get golang.org/x/tools/cmd/goimports
            go get golang.org/x/mobile/cmd/gomobile
            gomobile init
            GO111MODULE=on go get github.com/golang/protobuf/protoc-gen-go@v1.3.2
            GO111MODULE=on go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway@v1.14.3
            GO111MODULE=on go get github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger@v1.14.3
            GO111MODULE=on go get -u -v github.com/lightninglabs/falafel
            go get -d github.com/lightningnetwork/lnd
            cd $GOPATH/src/github.com/lightningnetwork/lnd && git checkout v0.12.0-beta && sed -i 's/use_prefix="0"/use_prefix="1"/g' mobile/gen_bindings.sh && make android tags="routerrpc walletrpc signrpc invoicesrpc"
      - name: Upload AAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: 'mobile/build/android/Lndmobile.aar'
      - uses: actions/checkout@v2
      - run: cp /go/src/github.com/lightningnetwork/lnd/mobile/build/android/Lndmobile.aar android/lndmobile
      - run: yarn
      - run: git submodule update --init
      - run: yarn build-tor-lib
      - run: yarn gen-proto
      - run: yarn test -w 1
      # Compile a bundled dev build https://stackoverflow.com/a/56520746
      - run: ./node_modules/.bin/react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
      - run: cd android && ./gradlew assembleChainmainnetNormalDebug && ./gradlew assembleChaintestnetNormalDebug

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: android-apk
          path: 'android/app/build/outputs'
