name: Run tests

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: yarn
      - run: yarn gen-proto
      - run: yarn test
